### ISSUE TITLE
Clocks 3.38

### ISSUE THREAD

**Issue by dchinmay2** [lonr/adwaita-one-dark#1]
Clocks 3.38 has a weird headerbar (is this the right term?)
![Screenshot from 2020-10-09 19-54-56](https://user-images.githubusercontent.com/36493671/95595124-75da0b80-0a69-11eb-804d-8970410ee7b5.png)

It should like this (Adwaita-dark)
![Screenshot from 2020-10-09 19-55-18](https://user-images.githubusercontent.com/36493671/95595137-78d4fc00-0a69-11eb-89e3-d0551feadd70.png)

**Comment by lonr** [comment]
Ubuntu's Yaru had the same issue: https://github.com/ubuntu/yaru/issues/2357 and https://github.com/ubuntu/yaru/issues/2060.  They fixed these by some [tweaks](https://github.com/ubuntu/yaru/pull/2382/files)
The upstream [said](https://gitlab.gnome.org/GNOME/gnome-clocks/-/issues/142#note_924433) that css of libhandy need to be bundled, but I have no idea how to do that. :confused:

**Comment by dchinmay2** [comment]
so do i just download this file, place it in src/gtk-3.0, add it to gtk-contained-dark.scss and run build.fish again?

**Comment by dchinmay2** [comment]
nvm they have too many yaru-specific variables i can't be bothered to adapt

**Comment by dchinmay2** [comment]
How do I start afresh from latest Adwaita? Just replace stuff in `src/gtk-3.0` with https://gitlab.gnome.org/GNOME/gtk/tree/master/gtk/theme/Adwaita or will I still have to bundle libhandy?

**Comment by lonr** [comment]
> How do I start afresh from latest Adwaita? Just replace stuff in `src/gtk-3.0` with https://gitlab.gnome.org/GNOME/gtk/tree/master/gtk/theme/Adwaita or will I still have to bundle libhandy?

I released a new version bundled libhandy and tested it in Feodra 33 Beta(don't need tweaks like yaru's). You can use it or refer to the new [README](https://github.com/lonr/adwaita-one-dark#how-to-build-by-hand) to make your own, or more quickly:

1. Copy stuff in [the directory of GTK theme](https://gitlab.gnome.org/GNOME/gtk/tree/master/gtk/theme/Adwaita) and [the directory of Handy theme for Adwaita](https://gitlab.gnome.org/GNOME/libhandy/-/tree/master/src/themes) to one folder. Ignore the duplicate `parse-sass.sh`
2. Modify `_colors.scss`(or whatever you want)
3. Remove `Adwaita-dark.css`
4. Edit `gtk-contained-dark.scss`: add `@import './Adwaita-dark';` above `@import 'colors-public';`
5. Generate the css file by `sassc -M -t compact gtk-contained-dark.scss gtk.css`
6. Move the generated `gtk.css` and `assets` folder to `your-theme-name/gtk-3.0/` and move `your-theme-name` folder to `~/.local/share/themes`

**Comment by dchinmay2** [comment]
This created more weird issues for me, like thiccc titlebars in non-gtk apps.

What worked perfectly was change colours in your theme (`src/gtk-3.0` and `src/gnome-shell`) and run `build.fish`

**Comment by lonr** [comment]
Maybe the main branches of those two repos are far ahead.

So it was solved?

**Comment by dchinmay2** [comment]
ye solved
