### ISSUE TITLE
Missing color scheme in top bar 

### ISSUE THREAD

**Issue by romanstingler** [lonr/adwaita-one-dark#22]
these are missing in Gnome 44

![Screenshot from 2023-05-21 22-55-09](https://github.com/lonr/adwaita-one-dark/assets/5576250/6ecbb7fc-d87c-4f55-b2dd-bb4969f9ec82)
![Screenshot from 2023-05-21 22-55-01](https://github.com/lonr/adwaita-one-dark/assets/5576250/4fa70883-3480-49db-b12a-6cea099da30b)

**Comment by lonr** [comment]
Thank you for your feedback. I have released a [new version](https://github.com/lonr/adwaita-one-dark/releases/tag/v0.44.1) to fix this issue.
