### ISSUE TITLE
Sidebar color no longer set

### ISSUE THREAD

**Issue by ByteDrummer** [lonr/adwaita-one-dark#25]
With a recent update, it seems the sidebar color got set back to default on a few applications, but Nautilus doesn't seem to be affected:

![Screenshot-2023-09-14_11:40:55](https://github.com/lonr/adwaita-one-dark/assets/14875006/ef52bb7d-ade6-453c-b5f3-9a252cf077c5)
![Screenshot-2023-09-14_11:46:56](https://github.com/lonr/adwaita-one-dark/assets/14875006/f6ec2171-2bfe-4af0-90df-0b16a9306a26)
![Screenshot-2023-09-14_11:47:38](https://github.com/lonr/adwaita-one-dark/assets/14875006/2e49f2b6-7768-48c7-86b8-2e4762d46c8c)

**Comment by lonr** [comment]
Please provide the names of several affected applications.

**Comment by ByteDrummer** [comment]
They are xdg-desktop-portal-gtk (first image) and Lutris (second image)

**Comment by ByteDrummer** [comment]
Found the fix for this issue here: https://github.com/GradienceTeam/Gradience/issues/828#issuecomment-1759547952

**Comment by lonr** [comment]
Thank you for your investigation.
The theme was updated to match GNOME 45. Therefore, the issue should be resolved.
The updated theme is available on the [release page](https://github.com/lonr/adwaita-one-dark/releases/tag/v0.45.0).
